#ifndef PANEL_GEOMETRY_H
#define PANEL_GEOMETRY_H
// PanelGeometry.h
//
// Triangulated outer-mold-line (OML) representation used by the Newtonian
// panel aerodynamics model. Panels can belong to a "group" (id 0 = fixed
// body, id > 0 = a deflectable flap) so that flap-deflection sweeps can be
// generated by rigidly rotating a subset of panels about a hinge axis
// without re-triangulating the vehicle.
//
// In production this mesh is populated either by the procedural placeholder
// in TestBodyGenerator.h or by importing a real triangulated export from
// OpenVSP/OpenRocket/CAD via StlMeshLoader.h.
//

#include <Eigen/Dense>
#include <string>
#include <unordered_map>
#include <vector>

namespace aero_model {

// A single flat triangular panel on the vehicle OML, in the BODY frame,
// prior to any flap deflection.
struct Panel {
    Eigen::Vector3d v0, v1, v2;
    Eigen::Vector3d centroid = Eigen::Vector3d::Zero();
    Eigen::Vector3d normal = Eigen::Vector3d::Zero();  // outward unit normal
    double area = 0.0;
    int group_id = 0;  // 0 = fixed body, >0 = deflectable flap group

    // Recomputes centroid, area, and outward normal from the current
    // vertex positions. Winding order (v0->v1->v2) must be consistent
    // with "outward" for all panels in the mesh.
    void recompute() {
        centroid = (v0 + v1 + v2) / 3.0;
        const Eigen::Vector3d e1 = v1 - v0;
        const Eigen::Vector3d e2 = v2 - v0;
        const Eigen::Vector3d cross = e1.cross(e2);
        area = 0.5 * cross.norm();
        normal = (area > 1e-14) ? Eigen::Vector3d(cross.normalized())
                                 : Eigen::Vector3d::Zero();
    }
};

// Metadata for a deflectable group of panels (e.g. one Starship-style flap).
struct PanelGroup {
    int id = 0;
    std::string name;
    Eigen::Vector3d hinge_point = Eigen::Vector3d::Zero();
    Eigen::Vector3d hinge_axis = Eigen::Vector3d::UnitY();  // must be unit norm
};

class PanelMesh {
public:
    void addPanel(const Panel& p) { panels_.push_back(p); }
    void addGroup(const PanelGroup& g) { groups_[g.id] = g; }

    const std::vector<Panel>& panels() const { return panels_; }
    const std::unordered_map<int, PanelGroup>& groups() const { return groups_; }

    // Returns a copy of the mesh with each flap group rigidly rotated by
    // its commanded deflection (radians) about its hinge point/axis via
    // Rodrigues' rotation formula. Group 0 (fixed body) is never rotated.
    // Groups not present in `deflections` are left at zero deflection.
    std::vector<Panel> deflected(
        const std::unordered_map<int, double>& deflections) const;

private:
    std::vector<Panel> panels_;
    std::unordered_map<int, PanelGroup> groups_;
};

}  // namespace aero_model

#endif // PANEL_GEOMETRY_H
